spring.application.name=smartqueue

# Database ? uses env var if set, falls back to local dev value
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/smartqueue}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:YOUR_PASSWORD_HERE}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# JWT
jwt.secret=${JWT_SECRET:NexLineSecretKey2026ThisMustBeAtLeast256BitsLongForHS256Algorithm}
jwt.expiration=86400000

# AI Service
ai.service.url=${AI_SERVICE_URL:http://localhost:8000}

spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
